### ISSUE TITLE
Snow layer of DHD problem

### ISSUE THREAD

**Issue by MineDragonCZ** [MineDragonCZ/Aunis1#10]
ID: 007
Log: https://hastebin.com/ukanuwumof.apache
Link: https://discord.com/channels/881802052488011837/898582264038973491/900439855677472808

Bug reporters: 
     Dr.McKay / Ironman Veronika YT#3068
     TRC#4660

**Comment by matousss** [comment]
log is not avaible and I was unable to reproduce the bug

**Comment by TheRedCreations** [comment]
[2021-10-27-2.log](https://github.com/MineDragonCZ/Aunis1/files/7549395/2021-10-27-2.log)
Log available

**Comment by matousss** [comment]
thank you

**Comment by matousss** [comment]
that's so weird, it looks like (if I understand it right) it tried to render dhd tileentity but there is no dhd block only air

**Comment by matousss** [comment]
at the coord was dhd in sgc, which no longer exist, but for some reason tileentity does

**Comment by matousss** [comment]
Probably fixed
