### ISSUE TITLE
Pegasus gate stuck open after failed dial

### ISSUE THREAD

**Issue by craft90** [MineDragonCZ/Aunis1#107]
I found an odd bug. I tried dialing a Pegasus gate with a Milky Way gate. When the first 6 chevrons was engaged, the Pegasus gate connected. No wormhole was formed but the shield activated and the glyphs lit up.  However instead of locking in the 7th POO glyph and thereby establish a connection, I hit the BRB. As expected the Milky Way gate shut down. However the Pegasus gate remained active! No wormhole mind you, but the shield was up and glyphs locked. Power was draining aswell. I couldn't use its DHD to dial out. The gate went back to normal operating after I dialed it again with another gate.

**Comment by MineDragonCZ** [comment]
fixed in dev version
