### ISSUE TITLE
aunis crashing my game in mid-load

### ISSUE THREAD

**Issue by kungstoffe08** [MineDragonCZ/Aunis1#109]
Aunis crashed my game when loading minecraft and gave me crash report 1), tried to fix by deleting aunis.cfg which helped so i edited the config through minecraft itself, so i closed Minecraft and then tried to start it again but it crashed mid-loading and gave me crash report 2)
i just want to play Aunis!!!
1) [crash-2022-02-07_19.12.31-client.txt](https://github.com/MineDragonCZ/Aunis1/files/8017779/crash-2022-02-07_19.12.31-client.txt)
2) [crash-2022-02-07_19.26.07-client.txt](https://github.com/MineDragonCZ/Aunis1/files/8017777/crash-2022-02-07_19.26.07-client.txt)

**Comment by MineDragonCZ** [comment]
Do u have tconstruct mod?

**Comment by kungstoffe08** [comment]
yes, is it a problem? these are mods that i am using, need some more informations??
![mody1](https://user-images.githubusercontent.com/79698504/152865161-0c0e9548-f7bd-451d-baec-273d247c183b.JPG)
![mody2](https://user-images.githubusercontent.com/79698504/152865171-c315dae1-aa3f-4407-b20d-9a68637d0397.JPG)
![mody3](https://user-images.githubusercontent.com/79698504/152865169-7d983638-7313-4855-913d-4c5d1a7d66cf.JPG)
![mody4](https://user-images.githubusercontent.com/79698504/152865167-4dad5833-62d7-45f2-8caa-77c111012f6b.JPG)

**Comment by MR-Spagetty** [comment]
Can you please send a picture of your aunis.cfg file

**Comment by kungstoffe08** [comment]
i thought it would be easier like this
[aunis.cfg.txt](https://github.com/MineDragonCZ/Aunis1/files/8018463/aunis.cfg.txt)

**Comment by MR-Spagetty** [comment]
Ok tc intigration is 9n

**Comment by kungstoffe08** [comment]
soo, solutin to my problem is to turn TC integration to false?

**Comment by MR-Spagetty** [comment]
No, I was checking if it was enabled as in the past it being DISABLED has crashed the game

**Comment by MineDragonCZ** [comment]
I probably know the proboem

**Comment by kungstoffe08** [comment]
so how do i fix it???? i want to play aunis very badly!!!!

**Comment by MineDragonCZ** [comment]
Enable tc integration

**Comment by TheRedCreations** [comment]
![grafik](https://user-images.githubusercontent.com/35812887/153013082-ea8fbac7-7e05-4594-b812-7c02fe5e575c.png)
Thats out of his cfg file. So it can't be cfg.

**Comment by MineDragonCZ** [comment]
Anyway, i will fix it on Friday

**Comment by kungstoffe08** [comment]
because dragon's _Enable tc integration_ confused me i did this:
![solution](https://user-images.githubusercontent.com/79698504/153014798-0c9cf595-9f94-4201-b42e-eb75c303068f.JPG) 
which came out to be temporary solution so i will keep it this way until someone finds better way...
