### ISSUE TITLE
cannot dial more than 5 chevrons by dhd if dialing Earth's address

### ISSUE THREAD

**Issue by captinwill** [MineDragonCZ/Aunis1#110]

**Comment by Cirrus-Updraft** [comment]
I encountered this bug, But only if I tried to dial the Earth address from the series,  After having set a milkyway gate to have that address, and only the Milkyway style gate, I didn’t test if it would happen after using an orlin gate to get to the nether

**Comment by captinwill** [comment]
i tested with the using the orlin gate to the nether and i could not dial more than five so i could come back

**Comment by Cirrus-Updraft** [comment]
So it seems that using the specific Earth address was broken

**Comment by captinwill** [comment]
that it is, as i tested another address and it worked.

**Comment by MineDragonCZ** [comment]
Try to break orlin and nether gates
After that run /sgfixnether 
Next place new orlin gate
