### ISSUE TITLE
Add Events/Signals (OC Integration)

### ISSUE THREAD

**Issue by Neico33** [MineDragonCZ/Aunis1#114]
Is it possible to extend the wiki to include the events/signals that trigger each block ?

Thanks, already.
Neico33

**Comment by MR-Spagetty** [comment]
It will be in th new wiki on the website for now you can find all the information you are looking for here: [https://mr-spagetty.github.io/AUNIS-Resurrection-wiki/integration_english.html#oc](https://mr-spagetty.github.io/AUNIS-Resurrection-wiki/integration_english.html#oc)

**Comment by MineDragonCZ** [comment]
Im working rn on new website on that will be also new Wiki....

**Comment by MineDragonCZ** [comment]
It will be there: https://aunis.cz/
