### ISSUE TITLE
Nether gate

### ISSUE THREAD

**Issue by MineDragonCZ** [MineDragonCZ/Aunis1#120]
https://github.com/MineDragonCZ/Aunis1/blob/f752346d71e39a6d7e94823d9480db079043d49d/src/main/java/mrjake/aunis/tileentity/stargate/StargateMilkyWayBaseTile.java#L162

Problem is in equals function. Rebuild it to check only first six symbols od dialed address

**Comment by aglarcz** [comment]
Tested after newest commit and still bugged.
