### ISSUE TITLE
Config isn´t working

### ISSUE THREAD

**Issue by Fredyman95** [MineDragonCZ/Aunis1#121]
Config setting of kawoosh invicible block isn´t working.

You can set block here, but gate will always destroy that block. Tested with rails, dirt, stone, blocks from aunis, blocks from diferent mods e.g. mekanism, enderio...

For information:
I set that config manualy in aunis.cfg - not working
I set that config in-game (mods settings) - not working
I tried without any brackets, with () {} [] , ;  and all combinations - not working

Rebooting of minecraft, rebooting of OS and cut out house from electricity and internet also not working. Even when I black out whole house for 15 minutes...

**Comment by MineDragonCZ** [comment]
send me your config, please

**Comment by Fredyman95** [comment]
Wait now I printed it out and try to smear it with cheetah blood

**Comment by Fredyman95** [comment]
# Configuration file

general {
    B:"Check for updates"=true

    # Valid values:
    # SMALL
    # MEDIUM
    # LARGE
    S:"Stargate size"=MEDIUM

    "stargate config options" {
        # If the incoming animations of gates generate issues, set it to false
        B:"Allow incoming animations"=true

        # If target gate is dialing and this option is set to true,
        # the target gate stop dialing and open incoming wormhole.
        # If this is set to false and the dialed gate dialing address,
        # the connection will not established.
        # If it cause issues, set it to false.
        B:"Connect to dialing gate"=true

        # Changing this option will require you to reload resources manually.
        # Just press F3+Q once in-game.
        B:"Disable animated Event Horizon"=true

        # Enable opening last chevron while dialing milkyway gate with dhd
        B:"Enable opening last chevron while dialing with dhd"=false

        # Speed up dialing with computer on MW gate
        B:"Faster MilkyWay gate computer dial"=false

        # Format: "modid:blockid[:meta]", for example: 
        # "minecraft:wool:7"
        # "minecraft:stone"
        S:"Kawoosh invincible blocks" <
            minecraft:golden_rail
            minecraft:detector_rail
            minecraft:rail
            minecraft:activator_rail
            enderio:block_exit_rail
            tconstruct:wood_rail
            tconstruct:wood_rail_trapdoor
         >

        # Speed factor of Milkyway and Universe gate
        # Min: 1.649999976158142
        # Max: 3.0
        D:"Milky/Uni gate speed factor"=1.7999999523162842

        # Min: 0
        # Max: 2147483647
        I:"Orlin's gate max open count"=2

        # Enable smooth dialing on pegasus DHD
        B:"Smooth dialing on pegasus gate DHD"=true

        # Below this biome temperature the gate will receive frosty texture.
        # Set to negative value to disable.
        D:"Temperature threshold for frosty overlay"=0.10000000149011612

        # Min: 0
        # Max: 64
        I:"Universe dialer max horizontal reach radius"=10
        I:"Universe dialer nearby radius"=1024

        # Change this to true, if you want to use 8 chevrons between pegasus and milkyway gates
        B:"Use 8 chevrons between MW and PG gates"=true

        ##########################################################################################################
        # biome overlay biome matches
        #--------------------------------------------------------------------------------------------------------#
        # This check comes last (after block is directly under sky (except Nether) and temperature is high enough).
        # You can disable the temperature check by setting it to a negative value.
        # Format: "modid:biomename", for example: 
        # "minecraft:dark_forest"
        # "minecraft:forest"
        ##########################################################################################################

        "biome overlay biome matches" {
            S:AGED <
             >
            S:FROST <
             >
            S:MOSSY <
                minecraft:jungle
                minecraft:jungle_hills
                minecraft:jungle_edge
                minecraft:mutated_jungle
                minecraft:mutated_jungle_edge
             >
            S:NORMAL <
             >
            S:SOOTY <
                minecraft:hell
             >
        }

        ##########################################################################################################
        # biome overlay override blocks
        #--------------------------------------------------------------------------------------------------------#
        # Format: "modid:blockid[:meta]", for example: 
        # "minecraft:wool:7"
        # "minecraft:stone"
        ##########################################################################################################

        "biome overlay override blocks" {
            S:AGED <
                minecraft:cobblestone
             >
            S:FROST <
                minecraft:ice
             >
            S:MOSSY <
                minecraft:vine
             >
            S:NORMAL <
                minecraft:stone
             >
            S:SOOTY <
                minecraft:coal_block
             >
        }

    }

    "iris/shield config options" {
        # Set it to true, if u want to bypass
        # shield/iris damage by creative gamemode
        B:"Allow creative bypass"=false
        B:"Can iris destroy blocks"=false

        # If set to 'false' player get killed by iris on entering event horizon
        B:"Iris kills at destination"=false

        # Min: 0
        # Max: 32
        I:"Maximum iris code length"=9

        # Energy/tick used for make shield closed
        # Min: 0
        # Max: 2147483647
        I:"Shield power draw"=20000

        # Durability of Titanium iris
        # set it to 0, if u want to make it unbreakable
        # Min: 0
        # Max: 2147483647
        I:"Titanium iris durability"=1500

        # Durability of Trinium iris
        # set it to 0, if u want to make it unbreakable
        # Min: 0
        # Max: 2147483647
        I:"Trinium iris durability"=4000

        # 0 - disables unbreaking on iris
        # 100 - unbreaking makes iris unbreakable
        # Min: 0
        # Max: 100
        I:"Unbreaking chance per level"=10
    }

    "dhd config options" {
        # Min: 1
        # Max: 2147483647
        I:"DHD range's radius horizontal"=10

        # Min: 1
        # Max: 2147483647
        I:"DHD range's radius vertical"=5

        # Min: 1
        # Max: 2147483647
        I:"DHD's max fluid capacity"=60000

        # Min: 1
        # Max: 2147483647
        I:"Energy per 1mB Naquadah"=10240

        # Energy per 1mB is multiplied by this
        # Consumed mB/t is equal to this
        # Min: 1
        # Max: 2147483647
        I:"Generation multiplier"=1

        # Disable this, to disable animation when dial gate with DHD (pegasus)
        B:"Pegasus DHD do dial animation"=true

        # Min: 0.0
        # Max: 1.0
        D:activationLevel=0.4

        # Min: 0.0
        # Max: 1.0
        D:deactivationLevel=0.98
    }

    "transport rings options" {
        B:"Ignore rings check for blocks to replace"=false

        # Min: 1
        # Max: 256
        I:"Rings range's radius horizontal"=50

        # Min: 1
        # Max: 256
        I:"Rings vertical reach"=256
    }

    "power draw options" {
        I:"Capacitors supported by Universe gates"=2

        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:"Orlin's gate energy multiplier"=2.0

        # Seconds of energy left before gate becomes unstable
        # Min: 1
        # Max: 2147483647
        I:"Stargate instability threshold"=20
        I:"Stargate instability threshold (seconds of energy left before gate becomes unstable)"=20

        # Min: 0
        # Max: 2147483647
        I:"Stargate wormhole open power draw"=4608

        # Min: 0
        # Max: 2147483647
        I:"Stargate wormhole sustain power draw"=2

        # Min: 0
        # Max: 2147483647
        I:"Stargate's internal buffer size"=71280000

        # Min: 1
        # Max: 2147483647
        I:"Stargate's max power throughput"=26360

        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:"Universe gate energy multiplier"=1.5

        # Min: 0
        # Max: 2147483647
        I:"ZPM Capacity"=2000000000
    }

    "debug options" {
        B:"Check gate merge"=true
        B:"Render bounding boxes"=false
        B:"Render invisible blocks"=false
        B:"Render whole kawoosh bounding box"=false
        B:"Show loading texture in log"=false
    }

    "mysterious page options" {
        # Min: 0.0
        # Max: 1.0
        D:"Chance of despawning DHD"=0.05

        # Min: 1
        # Max: 30000000
        I:"Max overworld XZ-coords generation"=7000

        # Min: 1
        # Max: 30000000
        I:"Min overworld XZ-coords generation"=2000

        # Min: 0
        # Max: 2147483647
        I:"Mysterious page cooldown"=60
    }

    "autoclose options" {
        B:"Autoclose enabled"=true

        # Min: 1
        # Max: 300
        I:"Seconds to autoclose with no players nearby"=5
    }

    "open time limit config" {
        B:"Enable max open time?"=true

        # (in seconds (2280 = 38 minutes))
        # Min: 5
        # Max: 3000
        I:"Maximum seconds of gate should be open"=600

        # Min: 0
        # Max: 50000
        I:"Power draw after opened time limit"=10000

        # U can use: closeGate, drawMorePower
        S:"What happens after the open time reach this time"=closeGate
    }

    "beamer options" {
        # Min: 1
        # Max: 2147483647
        I:"Energy buffer capacity"=17820000

        # Min: 1
        # Max: 2147483647
        I:"Energy buffer max transfer"=26360

        # Min: 1
        # Max: 2147483647
        I:"Fluid buffer capacity"=60000

        # Min: 1
        # Max: 2147483647
        I:"Fluid max transfer"=100

        # Min: 1
        # Max: 2147483647
        I:"Interval of signals being send to OC about transfers (in ticks)"=20

        # Min: 1
        # Max: 2147483647
        I:"Item max transfer"=4
        I:"Max gate-beamer distance"=10
        B:"Should the beam be responsive to fluid color"=true
    }

    "recipe options" {
    }

    "audio/video" {
        # Min: 0.0
        # Max: 1.0
        D:"Aunis volume"=1.0

        # Greater values render the Page more to the center of the screen, smaller render it closer to the borders.
        # 0 - for standard 16:9 (default),
        # 0.2 - for 4:3.
        D:"Notebook Page offset"=0.0

        # Min: 0.0
        # Max: 1.0
        D:"Notebook page Glyph transparency"=0.75
    }

    "worldgen config" {
        # Do you want to spawn naquadah ores in the Nether?
        B:"Enable Naquadah ore generation"=true

        # Do you want to spawn naquadah ores in the Overworld?
        B:"Enable Titanium ore generation"=true

        # Do you want to spawn trinium ores in the End?
        B:"Enable Trinium ore generation"=true
        I:"Naquadah max veins in chunk"=16
        I:"Naquadah vein size"=8
        I:"Titanium max veins in chunk"=8
        I:"Titanium vein size"=4
        I:"Trinium max veins in chunk"=4
        I:"Trinium vein size"=2
    }

    "mainmenu config" {
        # Disables showing custom main menu
        B:"Disable Aunis main menu - WARNING: Requires reloading"=true

        # Disables custom positions of buttons in main menu
        B:"Disable custom positions of buttons"=false

        # Enable/disable random gate overlays in main menu
        B:"Enable changing gate overlay"=true
        B:"Enable debug mode"=false

        # Do you want gate activation when starting game?
        B:"Enable event horizon in mainmenu"=false

        # Should ring of gate be static in main menu?
        B:"Enable gate rotation"=true
        B:"Play music in main menu"=true
    }

    "integrations config" {
        B:"Enable Open Computers integration"=true
        B:"Enable Thermal Expansion integration"=true
        B:"Enable Tinkers' Construct integration"=true
    }

    "developer options" {
        B:"Enable peg gates with myst pages"=false
    }

    "random incoming config" {
        # 10 = 1%
        # Min: 1
        # Max: 100
        I:"Chance of spawning"=1

        # Enable random incoming wormholes generator
        B:"Enable random incoming wormholes"=false

        # Format: "modid:entityid", for example: 
        # "minecraft:zombie"
        # "minecraft:creeper"
        S:"Entities to spawn" <
            minecraft:zombie
            minecraft:skeleton
         >
    }

}

**Comment by Fredyman95** [comment]
# Configuration file

general {
    B:"Check for updates"=true

    # Valid values:
    # SMALL
    # MEDIUM
    # LARGE
    S:"Stargate size"=MEDIUM

    "stargate config options" {
        # If the incoming animations of gates generate issues, set it to false
        B:"Allow incoming animations"=true

        # If target gate is dialing and this option is set to true,
        # the target gate stop dialing and open incoming wormhole.
        # If this is set to false and the dialed gate dialing address,
        # the connection will not established.
        # If it cause issues, set it to false.
        B:"Connect to dialing gate"=true

        # Changing this option will require you to reload resources manually.
        # Just press F3+Q once in-game.
        B:"Disable animated Event Horizon"=true

        # Enable opening last chevron while dialing milkyway gate with dhd
        B:"Enable opening last chevron while dialing with dhd"=false

        # Speed up dialing with computer on MW gate
        B:"Faster MilkyWay gate computer dial"=false

        # Format: "modid:blockid[:meta]", for example: 
        # "minecraft:wool:7"
        # "minecraft:stone"
        S:"Kawoosh invincible blocks" <
            minecraft:golden_rail
            minecraft:detector_rail
            minecraft:rail
            minecraft:activator_rail
            enderio:block_exit_rail
            tconstruct:wood_rail
            tconstruct:wood_rail_trapdoor
         >

        # Speed factor of Milkyway and Universe gate
        # Min: 1.649999976158142
        # Max: 3.0
        D:"Milky/Uni gate speed factor"=1.7999999523162842

        # Min: 0
        # Max: 2147483647
        I:"Orlin's gate max open count"=2

        # Enable smooth dialing on pegasus DHD
        B:"Smooth dialing on pegasus gate DHD"=true

        # Below this biome temperature the gate will receive frosty texture.
        # Set to negative value to disable.
        D:"Temperature threshold for frosty overlay"=0.10000000149011612

        # Min: 0
        # Max: 64
        I:"Universe dialer max horizontal reach radius"=10
        I:"Universe dialer nearby radius"=1024

        # Change this to true, if you want to use 8 chevrons between pegasus and milkyway gates
        B:"Use 8 chevrons between MW and PG gates"=true

        ##########################################################################################################
        # biome overlay biome matches
        #--------------------------------------------------------------------------------------------------------#
        # This check comes last (after block is directly under sky (except Nether) and temperature is high enough).
        # You can disable the temperature check by setting it to a negative value.
        # Format: "modid:biomename", for example: 
        # "minecraft:dark_forest"
        # "minecraft:forest"
        ##########################################################################################################

        "biome overlay biome matches" {
            S:AGED <
             >
            S:FROST <
             >
            S:MOSSY <
                minecraft:jungle
                minecraft:jungle_hills
                minecraft:jungle_edge
                minecraft:mutated_jungle
                minecraft:mutated_jungle_edge
             >
            S:NORMAL <
             >
            S:SOOTY <
                minecraft:hell
             >
        }

        ##########################################################################################################
        # biome overlay override blocks
        #--------------------------------------------------------------------------------------------------------#
        # Format: "modid:blockid[:meta]", for example: 
        # "minecraft:wool:7"
        # "minecraft:stone"
        ##########################################################################################################

        "biome overlay override blocks" {
            S:AGED <
                minecraft:cobblestone
             >
            S:FROST <
                minecraft:ice
             >
            S:MOSSY <
                minecraft:vine
             >
            S:NORMAL <
                minecraft:stone
             >
            S:SOOTY <
                minecraft:coal_block
             >
        }

    }

    "iris/shield config options" {
        # Set it to true, if u want to bypass
        # shield/iris damage by creative gamemode
        B:"Allow creative bypass"=false
        B:"Can iris destroy blocks"=false

        # If set to 'false' player get killed by iris on entering event horizon
        B:"Iris kills at destination"=false

        # Min: 0
        # Max: 32
        I:"Maximum iris code length"=9

        # Energy/tick used for make shield closed
        # Min: 0
        # Max: 2147483647
        I:"Shield power draw"=20000

        # Durability of Titanium iris
        # set it to 0, if u want to make it unbreakable
        # Min: 0
        # Max: 2147483647
        I:"Titanium iris durability"=1500

        # Durability of Trinium iris
        # set it to 0, if u want to make it unbreakable
        # Min: 0
        # Max: 2147483647
        I:"Trinium iris durability"=4000

        # 0 - disables unbreaking on iris
        # 100 - unbreaking makes iris unbreakable
        # Min: 0
        # Max: 100
        I:"Unbreaking chance per level"=10
    }

    "dhd config options" {
        # Min: 1
        # Max: 2147483647
        I:"DHD range's radius horizontal"=10

        # Min: 1
        # Max: 2147483647
        I:"DHD range's radius vertical"=5

        # Min: 1
        # Max: 2147483647
        I:"DHD's max fluid capacity"=60000

        # Min: 1
        # Max: 2147483647
        I:"Energy per 1mB Naquadah"=10240

        # Energy per 1mB is multiplied by this
        # Consumed mB/t is equal to this
        # Min: 1
        # Max: 2147483647
        I:"Generation multiplier"=1

        # Disable this, to disable animation when dial gate with DHD (pegasus)
        B:"Pegasus DHD do dial animation"=true

        # Min: 0.0
        # Max: 1.0
        D:activationLevel=0.4

        # Min: 0.0
        # Max: 1.0
        D:deactivationLevel=0.98
    }

    "transport rings options" {
        B:"Ignore rings check for blocks to replace"=false

        # Min: 1
        # Max: 256
        I:"Rings range's radius horizontal"=50

        # Min: 1
        # Max: 256
        I:"Rings vertical reach"=256
    }

    "power draw options" {
        I:"Capacitors supported by Universe gates"=2

        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:"Orlin's gate energy multiplier"=2.0

        # Seconds of energy left before gate becomes unstable
        # Min: 1
        # Max: 2147483647
        I:"Stargate instability threshold"=20
        I:"Stargate instability threshold (seconds of energy left before gate becomes unstable)"=20

        # Min: 0
        # Max: 2147483647
        I:"Stargate wormhole open power draw"=4608

        # Min: 0
        # Max: 2147483647
        I:"Stargate wormhole sustain power draw"=2

        # Min: 0
        # Max: 2147483647
        I:"Stargate's internal buffer size"=71280000

        # Min: 1
        # Max: 2147483647
        I:"Stargate's max power throughput"=26360

        # Min: 0.0
        # Max: 1.7976931348623157E308
        D:"Universe gate energy multiplier"=1.5

        # Min: 0
        # Max: 2147483647
        I:"ZPM Capacity"=2000000000
    }

    "debug options" {
        B:"Check gate merge"=true
        B:"Render bounding boxes"=false
        B:"Render invisible blocks"=false
        B:"Render whole kawoosh bounding box"=false
        B:"Show loading texture in log"=false
    }

    "mysterious page options" {
        # Min: 0.0
        # Max: 1.0
        D:"Chance of despawning DHD"=0.05

        # Min: 1
        # Max: 30000000
        I:"Max overworld XZ-coords generation"=7000

        # Min: 1
        # Max: 30000000
        I:"Min overworld XZ-coords generation"=2000

        # Min: 0
        # Max: 2147483647
        I:"Mysterious page cooldown"=60
    }

    "autoclose options" {
        B:"Autoclose enabled"=true

        # Min: 1
        # Max: 300
        I:"Seconds to autoclose with no players nearby"=5
    }

    "open time limit config" {
        B:"Enable max open time?"=true

        # (in seconds (2280 = 38 minutes))
        # Min: 5
        # Max: 3000
        I:"Maximum seconds of gate should be open"=600

        # Min: 0
        # Max: 50000
        I:"Power draw after opened time limit"=10000

        # U can use: closeGate, drawMorePower
        S:"What happens after the open time reach this time"=closeGate
    }

    "beamer options" {
        # Min: 1
        # Max: 2147483647
        I:"Energy buffer capacity"=17820000

        # Min: 1
        # Max: 2147483647
        I:"Energy buffer max transfer"=26360

        # Min: 1
        # Max: 2147483647
        I:"Fluid buffer capacity"=60000

        # Min: 1
        # Max: 2147483647
        I:"Fluid max transfer"=100

        # Min: 1
        # Max: 2147483647
        I:"Interval of signals being send to OC about transfers (in ticks)"=20

        # Min: 1
        # Max: 2147483647
        I:"Item max transfer"=4
        I:"Max gate-beamer distance"=10
        B:"Should the beam be responsive to fluid color"=true
    }

    "recipe options" {
    }

    "audio/video" {
        # Min: 0.0
        # Max: 1.0
        D:"Aunis volume"=1.0

        # Greater values render the Page more to the center of the screen, smaller render it closer to the borders.
        # 0 - for standard 16:9 (default),
        # 0.2 - for 4:3.
        D:"Notebook Page offset"=0.0

        # Min: 0.0
        # Max: 1.0
        D:"Notebook page Glyph transparency"=0.75
    }

    "worldgen config" {
        # Do you want to spawn naquadah ores in the Nether?
        B:"Enable Naquadah ore generation"=true

        # Do you want to spawn naquadah ores in the Overworld?
        B:"Enable Titanium ore generation"=true

        # Do you want to spawn trinium ores in the End?
        B:"Enable Trinium ore generation"=true
        I:"Naquadah max veins in chunk"=16
        I:"Naquadah vein size"=8
        I:"Titanium max veins in chunk"=8
        I:"Titanium vein size"=4
        I:"Trinium max veins in chunk"=4
        I:"Trinium vein size"=2
    }

    "mainmenu config" {
        # Disables showing custom main menu
        B:"Disable Aunis main menu - WARNING: Requires reloading"=true

        # Disables custom positions of buttons in main menu
        B:"Disable custom positions of buttons"=false

        # Enable/disable random gate overlays in main menu
        B:"Enable changing gate overlay"=true
        B:"Enable debug mode"=false

        # Do you want gate activation when starting game?
        B:"Enable event horizon in mainmenu"=false

        # Should ring of gate be static in main menu?
        B:"Enable gate rotation"=true
        B:"Play music in main menu"=true
    }

    "integrations config" {
        B:"Enable Open Computers integration"=true
        B:"Enable Thermal Expansion integration"=true
        B:"Enable Tinkers' Construct integration"=true
    }

    "developer options" {
        B:"Enable peg gates with myst pages"=false
    }

    "random incoming config" {
        # 10 = 1%
        # Min: 1
        # Max: 100
        I:"Chance of spawning"=1

        # Enable random incoming wormholes generator
        B:"Enable random incoming wormholes"=false

        # Format: "modid:entityid", for example: 
        # "minecraft:zombie"
        # "minecraft:creeper"
        S:"Entities to spawn" <
            minecraft:zombie
            minecraft:skeleton
         >
    }

}

**Comment by MineDragonCZ** [comment]
try to put them in quotes :)
