### ISSUE TITLE
thermal expansion recipes

### ISSUE THREAD

**Issue by aglarcz** [MineDragonCZ/Aunis1#122]
[aunis]: Successfully connected into Thermal Expansion!

Still magma crucible recipes are not working. Only sand into molten silicon works.

**Comment by aglarcz** [comment]
Circuit recipe also not working
![image](https://user-images.githubusercontent.com/17107410/158575528-ce9536db-1c55-44a7-b2f6-4abac98560d2.png)

**Comment by aglarcz** [comment]
4.9.4.3 compiled from this github, latest thermal and cofh core

**Comment by MineDragonCZ** [comment]
anyway, official versions can be found here: https://www.curseforge.com/minecraft/mc-mods/aunis-resurrection
