### ISSUE TITLE
not caused by AUNIS problem

### ISSUE THREAD

**Issue by kungstoffe08** [MineDragonCZ/Aunis1#123]
tried to play my modpack to test AUNIS with a lots of mods [(117 mods, about 283MB) wihout AUNIS] but something is making it crash midloading, i gave it all RAM i had (unsed warez launcher to find out the correct number code for this) but something is still crashing it. I have optifine installed but i don't think it's that core of the problem so can someone help??
[crash-2022-03-19_00.05.19-client.txt](https://github.com/MineDragonCZ/Aunis1/files/8308072/crash-2022-03-19_00.05.19-client.txt)

**Comment by MR-Spagetty** [comment]
If it isnt caused by aunis why are you reporting the crash here and if you ever report a crash ypu should always give the crash log

**Comment by MineDragonCZ** [comment]
First of all, if u r not using AUNIS, why r u reporting bugs here???

AnyWay, here is problem:
![image](https://user-images.githubusercontent.com/78699120/159115568-1c2e49dc-3577-4a73-a280-efaf8f3de052.png)
