### ISSUE TITLE
 Advanced Rocketry Support

### ISSUE THREAD

**Issue by lukasz4444** [MineDragonCZ/Aunis1#126]
Switching galaxies take more power.
Optional functionality one planet one stargate (like it was in sg1 where was two stargates on earth having the same address)

**Comment by MRSpagetty** [comment]
The first part is already possible through dimension groups which must be set in the config
The second is not going to happen

**Comment by MineDragonCZ** [comment]
> The first part is already possible through dimension groups which must be set in the config The second is not going to happen

I agree with MRSpagetty
