### ISSUE TITLE
Dailing When warping.

### ISSUE THREAD

**Issue by lukasz4444** [MineDragonCZ/Aunis1#131]
You can open wormhole when warping but in the show that was not possible.

Used mods

AdvancedRocketry 1.12.2-1.7.0-232 build -232 for 1.12.2 (I use this because it is stable)
aunis-1.12.2-4.9.4.2.jar

**Screenshot of bug**

![warpbug](https://user-images.githubusercontent.com/93074713/161104383-9e274cae-18c0-4121-a32d-3e472b437d52.png)

**Comment by MineDragonCZ** [comment]
I dont know where is the problem?

**Comment by lukasz4444** [comment]
I mean when dial on a warping spaceship in the show it dosen't worked.

**it was in the episode "Within the Serpent's Grasp"**

**Comment by MineDragonCZ** [comment]
Closing this issue....

**Comment by damianak22** [comment]
@MineDragonCZ 

To fix this add the following to attemptOpenDialed or a similar location.

            DimensionProperties destProps = zmaster587.advancedRocketry.dimension.DimensionManager.getInstance().getEffectiveDimId(targetGatePos.dimensionID, targetGatePos.gatePos);

            DimensionProperties sourceProps = zmaster587.advancedRocketry.dimension.DimensionManager.getInstance().getEffectiveDimId(world.provider.getDimension(), getPos());

            if (destProps == null || sourceProps == null) {
                // Failing due to source or destination gravity well missing. Only possible scenarios are in FTL or on a dimension that isnt mapped to AR.
                return new ResultTargetValid(StargateOpenResult.ABORTED_BY_EVENT, targetValid);
            }
