### ISSUE TITLE
Feature: IC2 integrations

### ISSUE THREAD

**Issue by DeathToCountry** [MineDragonCZ/Aunis1#136]
Hi, I only have a suggestion for the power in associations with other mods, and that is to incorporate compatibilities with Industrial Craft 2's power blocks

**Comment by JimSkywalker** [comment]
that is on the to do list already

**Comment by MineDragonCZ** [comment]
Hi, its already planned :)

**Comment by MineDragonCZ** [comment]
Duplicate of #86

**Comment by meclondrej** [comment]
the Energy Converters mod is the proper solution
