### ISSUE TITLE
Feature: Increase Wireless Range of UniDialer and GDO

### ISSUE THREAD

**Issue by TheRedCreations** [MineDragonCZ/Aunis1#139]
**Is your feature request related to a problem? Please describe.**
If your Gate and Computer are more than 20 Blocks away from each other, an wireless Message through the Gate won't reach the Computer. (Message send by UniDialer and GDO)

**Describe the solution you'd like**
Increase Range of GDO and UniDialer.

**Comment by MineDragonCZ** [comment]
i made it as config option

**Comment by TheRedCreations** [comment]
sweet. you did read my mind :D
