### ISSUE TITLE
Universe dialer crash

### ISSUE THREAD

**Issue by mecl2224** [MineDragonCZ/Aunis1#17]
Hello, me again with the same issue. When i take out universe dialer near an uni gate, crash. But i have more info! I noticed that dialer worked absolutely fine until i saved it in creative bar (that little "hotbar save" feature) and took it back. I will give a report.
[latest.log](https://github.com/MineDragonCZ/Aunis1/files/7419709/latest.log) 
Thx.

**Comment by matousss** [comment]
bump

**Comment by MR-Spagetty** [comment]
they were using Aunis+A4.9.jar just found it in their log
