### ISSUE TITLE
Feature: Sokar's Energy Weapon

### ISSUE THREAD

**Issue by lukasz4444** [MineDragonCZ/Aunis1#195]
**Is your feature request related to a problem? Please describe.**
In season 2 stargate sg1 sokar used energy weapon to melt the iris to get to the stargate command.

But in Aunis Resurrection (jsg) we dont have any thing stargate related to damage the iris, only thing that anyone can do to damage it is just using vanilla or moded entities such as items for an exaple and trow them to stargate with iris closed on other side.

**Describe the solution you'd like**
Adding Sokar's laser to game because it will be more like in stargate series way to damage iris on other side.

**Describe alternatives you've considered**
We have alternative already in game block that is suitable for this function, I am talking of course about a beamer block any change to make that function happen is to **add attack mode to it** and that's it.

Or if that cannot be added then please add that feature like it was in **sgcsm** (without the exploding part.)

**Additional context**
Here's a image how that was looking in the stargate show.

![Iris_under_attack](https://user-images.githubusercontent.com/93074713/198309627-e745d60c-68c9-4162-9cc9-fd3a200f8896.png)

**Comment by Angelafromlor** [comment]
![Screenshot_2022](https://user-images.githubusercontent.com/95143227/198314142-1a29ac59-d8c8-4e21-944d-71c64c43607a.png)
Frequently suggested.

**Comment by MineDragonCZ** [comment]
Closing, because its planned

**Comment by lukasz4444** [comment]
@Angelafromlor @MineDragonCZ  i am banned how i could possibly know?
