### ISSUE TITLE
Hopper item insert crash

### ISSUE THREAD

**Issue by kungstoffe08** [MineDragonCZ/Aunis1#32]
Itried to insert trinium iris into MW gate base block using hopper and when i tried to open the gate gui trough ring/chevron block my game crashed, crash-log inserted.
[crash-2021-11-01_19.24.51-client.txt](https://github.com/MineDragonCZ/Aunis1/files/7455406/crash-2021-11-01_19.24.51-client.txt)

**Comment by TheRedCreations** [comment]
Hopper inserted Iris into glyph slot in gate. The code wanted an Glyphcrystall inserted there (https://github.com/MineDragonCZ/Aunis1/blob/7959886d70ca116bc9c40589397b649616f6961e/src/main/java/mrjake/aunis/gui/container/StargateContainerGui.java#L182). Me as WGFS would say that's how it happend.

**Comment by matousss** [comment]
![image](https://user-images.githubusercontent.com/69765321/140614001-c371be25-bd8d-4abd-af72-94f080cfdff1.png)
bruh

**Comment by matousss** [comment]
now it won't crash but I have to find why it is happening

**Comment by matousss** [comment]
I disabled access by hopper and if you put item in gate before it won't crash your game.
