### ISSUE TITLE
combined with dalek mod

### ISSUE THREAD

**Issue by oddrobbia** [MineDragonCZ/Aunis1#33]
i combined the dalek mod with the aunis just for a test when i give myself the timelord 12 life and i survive the iris and cant use the stargate after i survived the iris just got the idea about can survive the iris with that yes can but after you cant use the stargate

**Comment by oddrobbia** [comment]
here is the log after i tested with the shield to https://paste.ee/p/nAaaH

**Comment by matousss** [comment]
![image](https://i.pinimg.com/originals/93/57/24/935724422be8f8c25510716306bed421.gif)

**Comment by matousss** [comment]
And it's already fixed wait for next update
