### ISSUE TITLE
Performance Issue with Pegasus DHD in Hotbar or when Accessing AUNIS Creative Tab

### ISSUE THREAD

**Issue by wdh7987** [MineDragonCZ/Aunis1#35]
Whenever the Pegasus DHD's icon is on the screen (either in the hotbar, inventory or when accessing the AUNIS creative tab, the framerate plummets by over 75%, as much as 90%. The instant it is removed the framerate is restored.

**Comment by MineDragonCZ** [comment]
Its because the model is big, so Harald must fix it...

**Comment by matousss** [comment]
Texture is still bugged but fps are fixed
