### ISSUE TITLE
unworking event horizon after closing gate

### ISSUE THREAD

**Issue by kungstoffe08** [MineDragonCZ/Aunis1#38]
i used mysterious page in nether and after opening it it closed right away (hope this is known already) but even horizon still was there though it wasn't working 
![2021-11-07_17 20 43](https://user-images.githubusercontent.com/79698504/140653227-f27b6060-ba30-44ae-851c-8626174fe504.png)

**Comment by MineDragonCZ** [comment]
setup dimeansions.yml and config.yml (energy part) :)

**Comment by lukasz4444** [comment]
i had this bug too if you open star gate and close it at the same time event horizon stays until re log.

**Comment by MineDragonCZ** [comment]
> i had this bug too if you open star gate and close it at the same time event horizon stays until re log.

hmmmm...

**Comment by MineDragonCZ** [comment]
Fixed
