### ISSUE TITLE
Universe dialer crash

### ISSUE THREAD

**Issue by mecl2224** [MineDragonCZ/Aunis1#39]
Hello, me again with the same issue. When i take out universe dialer near an uni gate, crash. But i have more info! I noticed that dialer worked absolutely fine until i saved it in creative bar (that little "hotbar save" feature) and took it back. I will give a report.
latest.log
Thx.

Sorry for my inactivity on github, this bug occurs in every unofficial version i ever played. (unofficial A4.6 and all above)

**Comment by MineDragonCZ** [comment]
dont use creative save bar :)

**Comment by mecl2224** [comment]
aaaah

**Comment by mecl2224** [comment]
is there any way of saving item and its NBT to somewhere except chest?

**Comment by kungstoffe08** [comment]
any block/item that have inventory i think
