### ISSUE TITLE
TechGuns2 projectiles crash server

### ISSUE THREAD

**Issue by matousss** [MineDragonCZ/Aunis1#40]
[crash-2021-11-08_22.34.25-server.txt](https://github.com/MineDragonCZ/Aunis1/files/7500375/crash-2021-11-08_22.34.25-server.txt)

**Comment by matousss** [comment]
Server crashed while trying to teleport projectile from TechGuns2 mod

**Comment by Lloydplays** [comment]
It doesn't happen because of anuis I tried it and my game still run so it must be another mod

**Comment by TheRedCreations** [comment]
this bug happens when the destination gate has an closed iris. and it's not only TG2. Even a MC Arrow crashed the server.

**Comment by TheRedCreations** [comment]
I think i found something. The setVelocity works only on client. Maybe we can use the projectile.motionX/Y/Z and set it to 0 to solve this.
![grafik](https://user-images.githubusercontent.com/35812887/160465382-cee207ca-4722-4dfc-b62a-fd374ca29959.png)
