### ISSUE TITLE
crash on singleplayer world

### ISSUE THREAD

**Issue by kungstoffe08** [MineDragonCZ/Aunis1#41]
i'm trying to play my singleplayer world where i made a lot of thing but don't want to lose it so i tested it on non-course forge launcher and it worked perfectly then i used that one (original removed) but it still crashed, can somebody help me??
[crash-2021-11-11_15.37.24-server.txt](https://github.com/MineDragonCZ/Aunis1/files/7521154/crash-2021-11-11_15.37.24-server.txt)

**Comment by matousss** [comment]
How exectly did you get the uni dialer?

**Comment by matousss** [comment]
You can fix by removing uni dialer from your inventory using nbt explorer.

**Comment by kungstoffe08** [comment]
> How exectly did you get the uni dialer?

normally: goes to creative mod inventory AUNIS section => took empty dialer out => started saving addresses

> You can fix by removing uni dialer from your inventory using nbt explorer.

how? like i have no idea how such a thing works

**Comment by matousss** [comment]
> how? like i have no idea how such a thing works

Try youtube for some tutorial or simplified version called [Universal Minecraft Editor](https://www.universalminecrafteditor.com)

![image](https://user-images.githubusercontent.com/69765321/141522061-a9ce40d2-284a-4be8-9015-4cb4b7498100.png)

**Comment by kungstoffe08** [comment]
fixed it by putting dialer into chest in original launcher and back in crashing launcher took it out of there
