### ISSUE TITLE
please add so the stargate AI can dial the stargate and if you don't have iris / shield, hostile mobs will enter through the gate, something like zombies, creepers etc if successful thease mobs can enter inside be vanilla mobs or vanilla mobs but with more health or just antything what is hositle mob.

### ISSUE THREAD

**Issue by lukasz4444** [MineDragonCZ/Aunis1#43]

**Comment by kungstoffe08** [comment]
why so long title??? couldn't you just made it like this:
title: hostile mod trough gate suggestion
description: please add so the stargate AI can dial the stargate and if you don't have iris / shield, hostile mobs will enter through the gate, something like zombies, creepers etc if successful thease mobs can enter inside be vanilla mobs or vanilla mobs but with more health or just antything what is hositle mob

**Comment by matousss** [comment]
already planed
