### ISSUE TITLE
DHD snow layer

### ISSUE THREAD

**Issue by MineDragonCZ** [MineDragonCZ/Aunis1#47]
this happened after get killed by iris
[crash-2021-11-14_15.52.36-client.txt](https://github.com/MineDragonCZ/Aunis1/files/7533977/crash-2021-11-14_15.52.36-client.txt)

**Comment by matousss** [comment]
Probably fixed

**Comment by MineDragonCZ** [comment]
Dik

**Comment by oddrobbia** [comment]
i see even minedragon make issue topic
