### ISSUE TITLE
Uhhhmmm

### ISSUE THREAD

**Issue by DeathToCountry** [MineDragonCZ/Aunis1#54]
So, in all honesty I'm not sure what to make of this. This comes from a modded server that I rent out of Apex Hosting,  I've restarted the server, and SR'ed the server and no change.
![2021-11-17_07 54 58](https://user-images.githubusercontent.com/16582184/142224120-6f8502d9-aae1-47ed-b907-e28f6bb76645.png)
![2021-11-17_07 55 05](https://user-images.githubusercontent.com/16582184/142224121-1cb4a1c7-2944-44b8-83ed-e7ebb9bce8ab.png)

**Comment by matousss** [comment]
Are you using the latest version? If yes then rebuild base block, it should fix it.

**Comment by matousss** [comment]
next time please provide some better title

**Comment by DeathToCountry** [comment]
I did actually try that, it did not do a single thing. I suspect, however, that it could be a bug due to the fact that I ACCIDENTALLY sent the Ender Dragon to Earth through a Gate.. And apologies, next time I'll give a better title

**Comment by matousss** [comment]
can you send me seed and exect coordinates of the gate?

**Comment by DeathToCountry** [comment]
Seed: -9187141716714352633
Exact coordinates: 61 71 -11, type MW facing south

**Comment by matousss** [comment]
I was unable to reproduce it, are you sure that server is using latest version?

**Comment by matousss** [comment]
I think the server has outdated Aunis
