### ISSUE TITLE
Transport rings can get duplicate addresses

### ISSUE THREAD

**Issue by catalyticenzyme** [MineDragonCZ/Aunis1#55]
**Describe the bug**
It is possible, despite the existing attempt at protection from duplicate addresses on transport rings, to get duplicate addresses in a network anyway. The exact way these duplicate addresses are handled also allows hijacking an existing transport ring network.

**To Reproduce**
- Place a transport ring down. We'll call this transport ring A.
- Place another transport ring down just inside its horizontal range. We'll call this transport ring B.
- Place a third transport ring down so that B can see it but A can't. We'll call this transport ring C.
- Give A and B addresses, and confirm you can travel between them.
- Give C the same address as A.
- **Bug** You can no longer reach A from B; attempts to reach its address send you to C.

**Expected behavior**
Trying to give C the same address as A should give a duplicate address error, like it would if they could see each other.

**Version**
AUNIS 4.9.1.1-alpha

**Comment by oddrobbia** [comment]
another example of useing the mod as its not intended

**Comment by TheRedCreations** [comment]
I was able to reproduce the bug. The last ring you configure (A or C) will be displayed at B
