### ISSUE TITLE
Translation problem

### ISSUE THREAD

**Issue by SGUDestiny** [MineDragonCZ/Aunis1#57]
Devs are frogetting to add item name to .lang files so translators can translate mod correctly.
Currently there are few items that we can't translate because of this

**Comment by matousss** [comment]
yes, you can, look on github for changes in en_us.lang

**Comment by matousss** [comment]
or I just wrote script to sync these files, should I mark not translated things with some character (or phrase)?

**Comment by matousss** [comment]
just uploaded synced files
