### ISSUE TITLE
Universe Dialer crash - generating gui entries

### ISSUE THREAD

**Issue by matousss** [MineDragonCZ/Aunis1#58]
here is the log i got crashed from the dialer even the event happened from prevent from crashing https://paste.ee/p/uhtcw

_Originally posted by @oddrobbia in https://github.com/MineDragonCZ/Aunis1/issues/51#issuecomment-970720681_

**Comment by matousss** [comment]
log is no longer avaible

**Comment by MineDragonCZ** [comment]
Fixed in new version
