### ISSUE TITLE
Dialing other dimensions turn off event horizon

### ISSUE THREAD

**Issue by MineDragonCZ** [MineDragonCZ/Aunis1#6]
ID: 004
Extends: 003
Log: https://hastebin.com/cedaladicu.apache
Link: https://discord.com/channels/881802052488011837/898582264038973491/898601061198213261

**Comment by matousss** [comment]
again broken link to log

**Comment by matousss** [comment]
Anybody can tell me how to reproduce it or provide log?

**Comment by MineDragonCZ** [comment]
Probably fixed
