### ISSUE TITLE
Iris OpenComputers control falsely claims success for a certain error type

### ISSUE THREAD

**Issue by catalyticenzyme** [MineDragonCZ/Aunis1#69]
In `mrjake.aunis.tileentity.stargate.StargateClassicBaseTile.sendIrisCode` (the implementation of `require("component").getPrimary("stargate").sendIrisCode` for OpenComputers programs), when you send an invalid argument type, it `return Object[]{true, "invalid_argument_type"};`, the same `true` as in `return Object[]{true, "success"};`, whereas for all other errors it `return Object[]{false, ...};`.

`return Object[]{true, "invalid_argument_type"};` should be changed to `return Object[]{false, "invalid_argument_type"};`, so that the first return value correctly indicates whether the call succeeded.

**Comment by matousss** [comment]
ok, now it will raise error like other methods when receive wrong argument type
