### ISSUE TITLE
Ticking block entity - gate

### ISSUE THREAD

**Issue by Fredyman95** [MineDragonCZ/Aunis1#74]
[crash-2021-12-15_22.13.24-server.txt](https://github.com/MineDragonCZ/Aunis1/files/7783261/crash-2021-12-15_22.13.24-server.txt)
[crash-2021-12-15_22.09.07-server.txt](https://github.com/MineDragonCZ/Aunis1/files/7783265/crash-2021-12-15_22.09.07-server.txt)

**Comment by MineDragonCZ** [comment]
Some info about it please?

**Comment by MineDragonCZ** [comment]
INFO:
- beamer error 
- i think fixed
