### ISSUE TITLE
Minecraft Crashed directly after Starting the Game since The AUNIS Update

### ISSUE THREAD

**Issue by Mirealis** [MineDragonCZ/Aunis1#82]
[crash-2022-01-02_23.22.02-client.txt](https://github.com/MineDragonCZ/Aunis1/files/7799880/crash-2022-01-02_23.22.02-client.txt)

**Comment by Trirene** [comment]
[crash-2022-01-02_14.40.50-client.txt](https://github.com/MineDragonCZ/Aunis1/files/7799893/crash-2022-01-02_14.40.50-client.txt)

**Comment by TheRedCreations** [comment]
Both crashes contain this (something about the new TR i guess): 
```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Aunis: Resurrection (aunis)
Caused by: java.lang.NoClassDefFoundError: mrjake/aunis/tileentity/transportrings/TransportRingsAncientTile
```

**Comment by MineDragonCZ** [comment]
Idk why

**Comment by MineDragonCZ** [comment]
https://stackoverflow.com/questions/34413/why-am-i-getting-a-noclassdeffounderror-in-java

**Comment by TheRedCreations** [comment]
This happend after deinstallation of OpenComputers. With OC there was no problem. Forge .5.2860
[crash-2022-01-03_15.58.47-client.txt](https://github.com/MineDragonCZ/Aunis1/files/7802550/crash-2022-01-03_15.58.47-client.txt)
Forge .5.2855 
[crash-2022-01-03_16.01.08-client.txt](https://github.com/MineDragonCZ/Aunis1/files/7802560/crash-2022-01-03_16.01.08-client.txt)

**Comment by MineDragonCZ** [comment]
fixed
