### ISSUE TITLE
Crash when interacting with pegasus gate 

### ISSUE THREAD

**Issue by IronmanVeronika** [MineDragonCZ/Aunis1#83]
i know u sayed u fixed it but its still there (yes i have newest version aunis-1.12.2-4.9.2.0-alpha)
[crash-2022-01-02_23.50.42-client.txt](https://github.com/MineDragonCZ/Aunis1/files/7799905/crash-2022-01-02_23.50.42-client.txt)
[crash-2022-01-02_23.54.16-client.txt](https://github.com/MineDragonCZ/Aunis1/files/7799906/crash-2022-01-02_23.54.16-client.txt)

**Comment by MineDragonCZ** [comment]
Rendering chevron of peg gate nullpointer

**Comment by MineDragonCZ** [comment]
probably fixed, waiting for another info
