### ISSUE TITLE
Orlin Gate doesn't work (also full model appears after just placing base and nothing else)

### ISSUE THREAD

**Issue by Paracanthus** [MineDragonCZ/Aunis1#88]
So when I place the Orlin gate, the full model appears, even though I haven't placed any of the ring blocks. Another issue is that when I put a button right next to the base block, the gate doesn't activate. A full video is this.
https://youtu.be/DuDIb4WcXwU

**Comment by MineDragonCZ** [comment]
Any problem in new version? (4.9.3.2)

**Comment by Paracanthus** [comment]
Okay so it turns out that it was my modpack, I was playing with a modified
version of zookeep-r dinos, but when I went into my own custom modpack it
worked like a charm
