### ISSUE TITLE
error in texture

### ISSUE THREAD

**Issue by VerkoCZ** [MineDragonCZ/Aunis1#90]
![image](https://user-images.githubusercontent.com/77051515/149968781-502229ca-6351-4943-8d2d-06d26e5b9eb9.png)

**Comment by HDL34** [comment]
It's not a big deal. It is the back of the gate that is hidden above the covering blocks creating the gate ramp.

**Comment by Lloydplays** [comment]
Doesn't even appear on my game so that means it's either was just with your game or it's a very low percentage of a glitch might already be patched unknowingly so deal with it

**Comment by MineDragonCZ** [comment]
Its caused by medium gate size
